version: '3.8'

services:
  # FastAPI Application
  app:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/enrich_ddf_floor2
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - SECRET_KEY=dev-secret-key-change-in-production
    depends_on:
      - db
      - redis
    networks:
      - enrich-network

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=enrich_ddf_floor2
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - enrich-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - enrich-network

  # Celery Worker
  celery:
    build:
      context: .
      target: development
    command: /app/.tmp/entry_celery.sh
    environment:
      - SECRET_KEY=dev-secret-key-change-in-production
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/enrich_ddf_floor2
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    depends_on:
      - db
      - redis
    networks:
      - enrich-network

  # Celery Flower (Task Monitor)
  flower:
    build:
      context: .
      target: development
    command: /app/.tmp/entry_flower.sh
    ports:
      - "5555:5555"
    environment:
      - SECRET_KEY=dev-secret-key-change-in-production
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    depends_on:
      - redis
    networks:
      - enrich-network

  # Prometheus (Metrics)
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - enrich-network

volumes:
  postgres_data:
  redis_data:
  prometheus_data:

networks:
  enrich-network:
    driver: bridge 