global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "enrich-ddf-floor2"
    static_configs:
      - targets: ["app:8000"]
    metrics_path: "/metrics"
    scrape_interval: 5s 